/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


/**
 *
 * @author danie
 */
public class mainFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        setAllInvisible();
        elvallalt.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooserPanel = new javax.swing.JPanel();
        ujTagLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        elvallaltLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        felvehetoLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        szabadsagLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        kerelmekLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        container = new javax.swing.JPanel();
        elvallalt = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        felveheto = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        szabadsag = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        kerelmek = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ujTag = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chooserPanel.setBackground(new java.awt.Color(217, 81, 78));
        chooserPanel.setForeground(new java.awt.Color(217, 81, 78));

        ujTagLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ujTagLabel.setText("                            Új tag felvétele");
        ujTagLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ujTagLabelMouseClicked(evt);
            }
        });

        elvallaltLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        elvallaltLabel.setText("                           Elvállalt munkák");
        elvallaltLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elvallaltLabelMouseClicked(evt);
            }
        });

        felvehetoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        felvehetoLabel.setText("                          Felvehetõ munkák");
        felvehetoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                felvehetoLabelMouseClicked(evt);
            }
        });

        szabadsagLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        szabadsagLabel.setText("                        Szabadság igénylése");
        szabadsagLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                szabadsagLabelMouseClicked(evt);
            }
        });

        kerelmekLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kerelmekLabel.setText("                        Szabadság kérelmek");
        kerelmekLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kerelmekLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout chooserPanelLayout = new javax.swing.GroupLayout(chooserPanel);
        chooserPanel.setLayout(chooserPanelLayout);
        chooserPanelLayout.setHorizontalGroup(
            chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserPanelLayout.createSequentialGroup()
                        .addComponent(ujTagLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserPanelLayout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserPanelLayout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserPanelLayout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserPanelLayout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserPanelLayout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chooserPanelLayout.createSequentialGroup()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addComponent(kerelmekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooserPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(elvallaltLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooserPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(felvehetoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooserPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(szabadsagLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        chooserPanelLayout.setVerticalGroup(
            chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooserPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kerelmekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ujTagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 439, Short.MAX_VALUE))
            .addGroup(chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooserPanelLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(elvallaltLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
            .addGroup(chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooserPanelLayout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(felvehetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(314, Short.MAX_VALUE)))
            .addGroup(chooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(chooserPanelLayout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(szabadsagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );

        container.setBackground(new java.awt.Color(42, 43, 45));

        elvallalt.setBackground(new java.awt.Color(42, 43, 45));
        elvallalt.setForeground(new java.awt.Color(0, 51, 51));

        jLabel6.setBackground(new java.awt.Color(217, 81, 78));
        jLabel6.setForeground(new java.awt.Color(217, 81, 78));
        jLabel6.setText("Elvállalt");

        javax.swing.GroupLayout elvallaltLayout = new javax.swing.GroupLayout(elvallalt);
        elvallalt.setLayout(elvallaltLayout);
        elvallaltLayout.setHorizontalGroup(
            elvallaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elvallaltLayout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1019, Short.MAX_VALUE))
        );
        elvallaltLayout.setVerticalGroup(
            elvallaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elvallaltLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        felveheto.setBackground(new java.awt.Color(42, 43, 45));
        felveheto.setRequestFocusEnabled(false);

        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("Felveheto");

        javax.swing.GroupLayout felvehetoLayout = new javax.swing.GroupLayout(felveheto);
        felveheto.setLayout(felvehetoLayout);
        felvehetoLayout.setHorizontalGroup(
            felvehetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(felvehetoLayout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel9)
                .addContainerGap(1074, Short.MAX_VALUE))
        );
        felvehetoLayout.setVerticalGroup(
            felvehetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(felvehetoLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel9)
                .addContainerGap(597, Short.MAX_VALUE))
        );

        szabadsag.setBackground(new java.awt.Color(42, 43, 45));
        szabadsag.setPreferredSize(new java.awt.Dimension(1298, 720));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(217, 81, 78));
        jLabel17.setText("Szabadság kérelem");

        jSeparator8.setBackground(new java.awt.Color(217, 81, 78));
        jSeparator8.setForeground(new java.awt.Color(217, 81, 78));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(217, 81, 78));
        jLabel18.setText("Önnek jelenleg ennyi szabadsága van: ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(217, 81, 78));
        jLabel20.setText("A szabadság végének dátuma:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(217, 81, 78));
        jLabel21.setText("A szabadság kezdésének dátuma:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(217, 81, 78));
        jLabel22.setText("A szabadság indoklása:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jSeparator9.setBackground(new java.awt.Color(217, 81, 78));
        jSeparator9.setForeground(new java.awt.Color(217, 81, 78));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(217, 81, 78));
        jLabel19.setText("A kérelem elbírálásáról email-ben értesítünk");

        javax.swing.GroupLayout szabadsagLayout = new javax.swing.GroupLayout(szabadsag);
        szabadsag.setLayout(szabadsagLayout);
        szabadsagLayout.setHorizontalGroup(
            szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(szabadsagLayout.createSequentialGroup()
                .addContainerGap(518, Short.MAX_VALUE)
                .addGroup(szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, szabadsagLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(661, 661, 661))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, szabadsagLayout.createSequentialGroup()
                        .addGroup(szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(szabadsagLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(77, 77, 77)))
                        .addGap(485, 485, 485))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, szabadsagLayout.createSequentialGroup()
                        .addGroup(szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, szabadsagLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, szabadsagLayout.createSequentialGroup()
                                .addGroup(szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addGap(38, 38, 38)
                                .addGroup(szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, szabadsagLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(123, 123, 123)))
                        .addGap(517, 517, 517))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, szabadsagLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(600, 600, 600))))
        );
        szabadsagLayout.setVerticalGroup(
            szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(szabadsagLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jLabel18)
                .addGap(88, 88, 88)
                .addGroup(szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(szabadsagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jLabel22)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(41, 41, 41))
        );

        kerelmek.setBackground(new java.awt.Color(42, 43, 45));

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("KERELMEK");

        javax.swing.GroupLayout kerelmekLayout = new javax.swing.GroupLayout(kerelmek);
        kerelmek.setLayout(kerelmekLayout);
        kerelmekLayout.setHorizontalGroup(
            kerelmekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kerelmekLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel7)
                .addContainerGap(1050, Short.MAX_VALUE))
        );
        kerelmekLayout.setVerticalGroup(
            kerelmekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kerelmekLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel7)
                .addContainerGap(569, Short.MAX_VALUE))
        );

        ujTag.setBackground(new java.awt.Color(42, 43, 45));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(217, 81, 78));
        jLabel10.setText("Ha fel szeretne venni egy új tagot a rendszerbe, adja meg az adatait! ");

        jSeparator6.setBackground(new java.awt.Color(217, 81, 78));
        jSeparator6.setForeground(new java.awt.Color(217, 81, 78));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(217, 81, 78));
        jLabel11.setText("Név :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(217, 81, 78));
        jLabel12.setText("Beosztás :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(217, 81, 78));
        jLabel13.setText("Fizetés :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(217, 81, 78));
        jLabel14.setText("Város :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(217, 81, 78));
        jLabel15.setText(" Jelszó :");

        jButton1.setBackground(new java.awt.Color(217, 81, 78));
        jButton1.setText("Tag felvétele");

        jSeparator7.setBackground(new java.awt.Color(217, 81, 78));
        jSeparator7.setForeground(new java.awt.Color(217, 81, 78));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(217, 81, 78));
        jLabel16.setText("Az adatokat késõbb még modosíthatja");

        javax.swing.GroupLayout ujTagLayout = new javax.swing.GroupLayout(ujTag);
        ujTag.setLayout(ujTagLayout);
        ujTagLayout.setHorizontalGroup(
            ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ujTagLayout.createSequentialGroup()
                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ujTagLayout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(ujTagLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ujTagLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel16))))
                    .addGroup(ujTagLayout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ujTagLayout.createSequentialGroup()
                                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ujTagLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel12)
                                    .addGroup(ujTagLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))))
                                .addGap(76, 76, 76)
                                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(495, Short.MAX_VALUE))
        );
        ujTagLayout.setVerticalGroup(
            ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ujTagLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(ujTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elvallalt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(felveheto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(szabadsag, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(kerelmek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                    .addComponent(ujTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elvallalt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(felveheto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(szabadsag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(kerelmek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ujTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elvallaltLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elvallaltLabelMouseClicked
        setAllInvisible();
        elvallalt.setVisible(true);
    }//GEN-LAST:event_elvallaltLabelMouseClicked

    private void felvehetoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_felvehetoLabelMouseClicked
        setAllInvisible();
        felveheto.setVisible(true);
    }//GEN-LAST:event_felvehetoLabelMouseClicked

    private void szabadsagLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_szabadsagLabelMouseClicked
        setAllInvisible();
        szabadsag.setVisible(true);
    }//GEN-LAST:event_szabadsagLabelMouseClicked

    private void kerelmekLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kerelmekLabelMouseClicked
        setAllInvisible();
        kerelmek.setVisible(true);
    }//GEN-LAST:event_kerelmekLabelMouseClicked

    private void ujTagLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ujTagLabelMouseClicked
        setAllInvisible();
        ujTag.setVisible(true);
    }//GEN-LAST:event_ujTagLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }
    public void setAllInvisible(){
        elvallalt.setVisible(false);
        felveheto.setVisible(false);
        kerelmek.setVisible(false);
        szabadsag.setVisible(false);
        ujTag.setVisible(false);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chooserPanel;
    private javax.swing.JPanel container;
    private javax.swing.JPanel elvallalt;
    private javax.swing.JLabel elvallaltLabel;
    private javax.swing.JPanel felveheto;
    private javax.swing.JLabel felvehetoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel kerelmek;
    private javax.swing.JLabel kerelmekLabel;
    private javax.swing.JPanel szabadsag;
    private javax.swing.JLabel szabadsagLabel;
    private javax.swing.JPanel ujTag;
    private javax.swing.JLabel ujTagLabel;
    // End of variables declaration//GEN-END:variables
}

